### ISSUE TITLE
Unclear problem description with missing closing //

### ISSUE THREAD

**Issue by caillette** [caillette/novelang#114]
With a Novella just made of this:
    (//oops)
We get:
    org.antlr.runtime.tree.RewriteEmptyStreamException: rule spreadBlockBody
      at org.antlr.runtime.tree.RewriteRuleElementStream._next(RewriteRuleElementStream.java:158)
      at org.antlr.runtime.tree.RewriteRuleElementStream.nextTree(RewriteRuleElementStream.java:145)
      at org.novelang.parser.antlr.NovelangParser.parenthesizedSpreadblock(NovelangParser.java:6800)
      at org.novelang.parser.antlr.NovelangParser.delimitedSpreadblock(NovelangParser.java:2860)
      at org.novelang.parser.antlr.NovelangParser.mixedDelimitedSpreadBlock(NovelangParser.java:3758)
      at org.novelang.parser.antlr.NovelangParser.paragraph(NovelangParser.java:2368)
      at org.novelang.parser.antlr.NovelangParser.novella(NovelangParser.java:924)
      at org.novelang.parser.antlr.DelegatingPartParser.callParserMethod(DelegatingPartParser.java:38)
      at org.novelang.parser.antlr.AbstractDelegatingParser.parse(AbstractDelegatingParser.java:81)
      at org.novelang.common.AbstractSourceReader.parse(AbstractSourceReader.java:160)
      at org.novelang.novella.Novella.createTree(Novella.java:107)
      at org.novelang.novella.Novella.(Novella.java:97)
      at org.novelang.produce.DocumentProducer.createRenderable(DocumentProducer.java:201)
      at org.novelang.daemon.DocumentHandler.handle(DocumentHandler.java:116)
      at org.novelang.daemon.DocumentHandler.doHandle(DocumentHandler.java:83)
      at org.novelang.daemon.GenericHandler.handle(GenericHandler.java:54)
      at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:151)
      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
      at org.eclipse.jetty.server.Server.handle(Server.java:352)
      at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
      at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051)
      at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
      at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
      at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
      at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
      at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
      at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
      at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
      at java.lang.Thread.run(Thread.java:619)

**Comment by caillette** [comment]
After fixing #100 we now get a more polite message with line and column.
