### ISSUE TITLE
Some XSLT breaks the Novelang Ant Task

### ISSUE THREAD

**Issue by caillette** [caillette/novelang#86]
The <code>src/doc/style/announcement-plaintext.xsl</code> stylesheet seems to break when passed to the NovelangTask. See the stack trace.

```
BUILD FAILED
java.lang.VerifyError: (class: GregorSamsa, method: applyTemplates_3 signature:
(Lcom/sun/org/apache/xalan/internal/xsltc/DOM;Lcom/sun/org/apache/xml/internal/dtm/DTMAxisIterator;Lcom/sun/org/apache/xml/internal/serializer/SerializationHandler;)V) 
Illegal local variable number
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2357)
    at java.lang.Class.getConstructor0(Class.java:2671)
    at java.lang.Class.newInstance0(Class.java:321)
    at java.lang.Class.newInstance(Class.java:303)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.getTransletInstance(TemplatesImpl.java:353)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.newTransformer(TemplatesImpl.java:382)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformerHandler(TransformerFactoryImpl.java:925)
    at novelang.rendering.XslWriter.createContentHandler(XslWriter.java:184)
    at novelang.rendering.XmlWriter.startWriting(XmlWriter.java:75)
    at novelang.rendering.GenericRenderer.render(GenericRenderer.java:63)
    at novelang.produce.DocumentProducer.serve(DocumentProducer.java:148)
    at novelang.produce.DocumentProducer.access$000(DocumentProducer.java:52)
    at novelang.produce.DocumentProducer$1Serve.with(DocumentProducer.java:88)
    at novelang.produce.DocumentProducer.produce(DocumentProducer.java:122)
    at novelang.produce.DocumentProducer.produce(DocumentProducer.java:74)
    at novelang.batch.NovelangTask.produce(NovelangTask.java:208)
    at novelang.batch.NovelangTask.execute(NovelangTask.java:183)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:592)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:357)
    at org.apache.tools.ant.Target.performTasks(Target.java:385)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
    at org.apache.tools.ant.Main.runBuild(Main.java:758)
    at org.apache.tools.ant.Main.startAnt(Main.java:217)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
```

**Comment by caillette** [comment]
Seems to happen because Xalan's XLSTC (dynamic code generation) fails because generated class has bad name. Googling on the exception message, it appears that Cocoon developers already faced this problem:
http://osdir.com/ml/text.xml.cocoon.devel/2002-04/msg00350.html

But the <code>annoucement-html.xsl</code> currently works even if it imports other stylesheets.

**Comment by caillette** [comment]
Under some other circumstances (like using one of Novelang's standard HTML stylesheets) the bug described here happens:
http://forums.sun.com/thread.jspa?threadID=5134880

**Comment by caillette** [comment]
Workaround along with 0.45.0 by launching another process.

**Comment by caillette** [comment]
Anyways there is no Ant task now we've migrated to Maven!
